import { createElement, useCallback, useEffect, useState } from "react";
import { Banknote, Clock3, LockKeyhole, ReceiptText, WalletCards } from "lucide-react";
import { API_URL } from "../api/authenticatedFetch";
import { Feedback } from "./ui/Feedback";
const dinheiro = (v) => `${Number(v || 0).toLocaleString("pt-MZ", { minimumFractionDigits: 2 })} MZN`;

export default function Caixa() {
  const [dados, setDados] = useState(null); const [valor, setValor] = useState(""); const [erro, setErro] = useState(""); const [sucesso, setSucesso] = useState(""); const [loading, setLoading] = useState(false);
  const carregar = useCallback(async () => { try { const r = await fetch(`${API_URL}/caixa`); const d = await r.json(); if (!r.ok) throw new Error(d.erro); setDados(d); } catch (e) { setErro(e.message || "Não foi possível carregar o caixa."); } }, []);
  useEffect(() => { carregar(); }, [carregar]);
  const aberto = dados?.caixa?.estado === "aberto"; const esperado = Number(dados?.caixa?.valor_abertura || 0) + Number(dados?.totais?.dinheiro || 0);
  const executar = async () => { setLoading(true); setErro(""); setSucesso(""); try { const url = aberto ? `${API_URL}/caixa/${dados.caixa.id}/fechar` : `${API_URL}/caixa/abrir`; const corpo = aberto ? { valor_fecho: Number(valor) } : { valor_abertura: Number(valor || 0) }; const r = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(corpo) }); const d = await r.json(); if (!r.ok) throw new Error(d.erro); const diferenca = Number(d.fecho?.diferenca || 0); setSucesso(aberto ? `Caixa fechado. Diferença apurada: ${dinheiro(diferenca)}.` : "Caixa aberto e pronto para vender."); setValor(""); await carregar(); } catch (e) { setErro(e.message); } finally { setLoading(false); } };
  return <main className="commerce-page h-dvh min-w-0 flex-1 overflow-auto p-4 sm:p-6 lg:p-8">
    <header className="commerce-header"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Operação diária</p><h1>Caixa</h1><p className="text-slate-600">Acompanhe valores recebidos e faça o fecho com confiança.</p></header>
    <div className="my-5 space-y-3"><Feedback tipo="erro">{erro}</Feedback><Feedback tipo="sucesso">{sucesso}</Feedback></div>
    <section className="commerce-panel max-w-4xl overflow-hidden"><div className={`flex flex-wrap items-center justify-between gap-4 p-6 sm:p-8 ${aberto ? "bg-gradient-to-r from-emerald-600 to-teal-600 text-white" : "bg-gradient-to-r from-slate-800 to-slate-700 text-white"}`}><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-white/15"><Banknote size={28}/></span><div><p className="text-sm text-white/70">Estado atual</p><h2 className="text-2xl font-extrabold">{dados ? (aberto ? "Caixa aberto" : "Caixa fechado") : "A carregar..."}</h2></div></div>{aberto && <div className="text-right"><p className="text-sm text-white/70">Aberto por</p><b>{dados.caixa.operador}</b><p className="mt-1 flex items-center justify-end gap-1 text-xs text-white/70"><Clock3 size={13}/>{new Date(dados.caixa.aberto_em).toLocaleString("pt-MZ")}</p></div>}</div>
      {aberto && <div className="grid gap-3 p-5 sm:grid-cols-3 sm:p-7"><Metrica icon={ReceiptText} label="Vendas no caixa" value={dados.totais.vendas}/><Metrica icon={WalletCards} label="Total vendido" value={dinheiro(dados.totais.total)}/><Metrica icon={Banknote} label="Dinheiro esperado" value={dinheiro(esperado)} destaque/></div>}
      <div className="border-t border-slate-100 p-5 sm:p-7"><div className="mb-4 flex items-start gap-3"><span className="rounded-xl bg-slate-100 p-2 text-slate-600"><LockKeyhole size={19}/></span><div><h3 className="font-bold text-slate-900">{aberto ? "Fechar caixa" : "Abrir novo caixa"}</h3><p className="text-sm text-slate-500">{aberto ? "Conte o dinheiro físico antes de confirmar o fecho." : "Informe o fundo inicial disponível para trocos."}</p></div></div><label className="block max-w-md text-sm font-semibold text-slate-700">{aberto ? "Valor contado no fecho" : "Valor inicial"}<div className="relative mt-1"><input type="number" min="0" step="0.01" value={valor} onChange={(e) => setValor(e.target.value)} placeholder="0,00" className="w-full rounded-xl border border-slate-200 bg-slate-50 p-3 pr-16"/><span className="absolute right-3 top-3 text-sm font-bold text-slate-400">MZN</span></div></label><button type="button" onClick={executar} disabled={loading || !dados || (aberto && valor === "")} className={`mt-4 w-full max-w-md rounded-xl p-3 font-bold text-white shadow-lg disabled:opacity-50 ${aberto ? "bg-slate-800 shadow-slate-200 hover:bg-slate-900" : "bg-emerald-600 shadow-emerald-100 hover:bg-emerald-700"}`}>{loading ? "A processar..." : aberto ? "Confirmar fecho" : "Abrir caixa"}</button></div>
    </section>
  </main>;
}
function Metrica({ icon, label, value, destaque }) { return <article className={`rounded-2xl border p-4 ${destaque ? "border-indigo-100 bg-indigo-50" : "border-slate-100 bg-slate-50"}`}>{createElement(icon, { size: 19, className: destaque ? "text-indigo-600" : "text-slate-400" })}<small className="mt-3 block text-slate-500">{label}</small><b className="mt-1 block text-lg text-slate-900">{value}</b></article>; }
