import { useEffect, useState } from "react";
import { Building2, KeyRound, Save, UserRound } from "lucide-react";
import { API_URL } from "../api/authenticatedFetch";
import { useAuth } from "../features/auth/AuthContext";

const Input = ({ label, ...props }) => <label className="block text-sm font-medium text-slate-700"><span>{label}</span><input {...props} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /></label>;

export default function Perfil() {
  const { usuario, iniciarSessao } = useAuth();
  const [conta, setConta] = useState(null); const [erro, setErro] = useState(""); const [mensagem, setMensagem] = useState(""); const [salvando, setSalvando] = useState("");
  const carregar = async () => { const r = await fetch(`${API_URL}/auth/minha-conta`); const d = await r.json(); if (!r.ok) throw new Error(d.message); setConta(d.conta); };
  useEffect(() => { carregar().catch((e) => setErro(e.message)); }, []);
  const enviar = async (rota, dados, tipo) => { setErro(""); setMensagem(""); setSalvando(tipo); try { const r = await fetch(`${API_URL}/auth/${rota}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(dados) }); const d = await r.json(); if (!r.ok) throw new Error(d.message); if (tipo === "senha" && d.token) iniciarSessao({ token: d.token, usuario }); setMensagem(d.message); return d; } finally { setSalvando(""); } };
  if (!conta) return <main className="flex flex-1 items-center justify-center bg-slate-50"><p className="rounded-xl bg-white p-5 text-slate-600 shadow-sm">{erro || "A carregar perfil..."}</p></main>;
  return <main className="flex-1 overflow-auto bg-slate-50 p-5 md:p-8"><header><p className="text-sm font-semibold text-indigo-600">DEFINIÇÕES</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Perfil e empresa</h1><p className="mt-2 text-slate-600">Mantenha os seus dados e os dados legais da empresa atualizados.</p></header>{erro && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{erro}</p>}{mensagem && <p className="mt-5 rounded-xl bg-emerald-50 p-4 text-emerald-800">{mensagem}</p>}<div className="mt-7 grid max-w-5xl gap-6 lg:grid-cols-2">
    <form className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm" onSubmit={async (e) => { e.preventDefault(); try { const d = await enviar("perfil", { nome: conta.nome, email: conta.email }, "perfil"); iniciarSessao({ token: localStorage.getItem("bmanager.token"), usuario: { ...usuario, ...d.usuario } }); } catch (err) { setErro(err.message); } }}><div className="flex items-center gap-3"><span className="rounded-xl bg-indigo-100 p-2 text-indigo-600"><UserRound size={20}/></span><div><h2 className="font-semibold text-slate-900">Dados pessoais</h2><p className="text-sm text-slate-500">Informações da sua conta.</p></div></div><div className="mt-6 space-y-4"><Input label="Nome completo" value={conta.nome} onChange={(e) => setConta({ ...conta, nome: e.target.value })} required/><Input label="E-mail" type="email" value={conta.email} onChange={(e) => setConta({ ...conta, email: e.target.value })} required/></div><button disabled={salvando !== ""} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 font-semibold text-white hover:bg-indigo-700 disabled:opacity-60"><Save size={17}/>{salvando === "perfil" ? "A guardar..." : "Guardar perfil"}</button></form>
    <form className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm" onSubmit={async (e) => { e.preventDefault(); const formulario = e.currentTarget; try { await enviar("senha", { senhaAtual: formulario.senhaAtual.value, novaSenha: formulario.novaSenha.value }, "senha"); formulario.reset(); } catch (err) { setErro(err.message); } }}><div className="flex items-center gap-3"><span className="rounded-xl bg-amber-100 p-2 text-amber-600"><KeyRound size={20}/></span><div><h2 className="font-semibold text-slate-900">Segurança</h2><p className="text-sm text-slate-500">Altere a senha da sua conta.</p></div></div><div className="mt-6 space-y-4"><Input label="Senha atual" name="senhaAtual" type="password" required/><Input label="Nova senha" name="novaSenha" type="password" minLength="6" required/></div><button disabled={salvando !== ""} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 font-semibold text-white hover:bg-slate-800 disabled:opacity-60"><KeyRound size={17}/>{salvando === "senha" ? "A atualizar..." : "Atualizar senha"}</button></form>
    {conta.role === "admin" && <form className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2" onSubmit={async (e) => { e.preventDefault(); try { await enviar("empresa", { nome: conta.empresa_nome, nuit: conta.nuit, email: conta.empresa_email, telefone: conta.empresa_telefone, endereco: conta.empresa_endereco }, "empresa"); } catch (err) { setErro(err.message); } }}><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-100 p-2 text-emerald-600"><Building2 size={20}/></span><div><h2 className="font-semibold text-slate-900">Dados legais da empresa</h2><p className="text-sm text-slate-500">Estes dados aparecem nas faturas geradas.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Input label="Nome da empresa" value={conta.empresa_nome} onChange={(e) => setConta({ ...conta, empresa_nome: e.target.value })} required/><Input label="NUIT" value={conta.nuit || ""} onChange={(e) => setConta({ ...conta, nuit: e.target.value })}/><Input label="E-mail comercial" type="email" value={conta.empresa_email || ""} onChange={(e) => setConta({ ...conta, empresa_email: e.target.value })}/><Input label="Telefone" value={conta.empresa_telefone || ""} onChange={(e) => setConta({ ...conta, empresa_telefone: e.target.value })}/><div className="md:col-span-2"><Input label="Endereço" value={conta.empresa_endereco || ""} onChange={(e) => setConta({ ...conta, empresa_endereco: e.target.value })}/></div></div><button disabled={salvando !== ""} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 font-semibold text-white hover:bg-emerald-700 disabled:opacity-60"><Save size={17}/>{salvando === "empresa" ? "A guardar..." : "Guardar dados da empresa"}</button></form>}
  </div></main>;
}
