import { useState } from "react";
import { Link } from "react-router-dom";
import { API_URL as API } from "../api/authenticatedFetch";
export default function RecuperarSenha() {
  const token = new URLSearchParams(window.location.search).get("token");
  const [valor, setValor] = useState(""); const [mensagem, setMensagem] = useState(""); const [erro, setErro] = useState(""); const [enviando, setEnviando] = useState(false);
  const enviar = async (event) => { event.preventDefault(); setErro(""); setMensagem(""); setEnviando(true); try { const r = await fetch(`${API}${token ? "/auth/redefinir-senha" : "/auth/recuperar-senha"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(token ? { token, senha: valor } : { email: valor }) }); const d = await r.json(); if (!r.ok) throw new Error(d.message || d.erro || "Não foi possível concluir a solicitação."); setMensagem(d.message); if (token) setValor(""); } catch (error) { setErro(error.message); } finally { setEnviando(false); } };
  return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><form onSubmit={enviar} className="w-full max-w-md rounded-2xl bg-white p-6 shadow"><h1 className="text-xl font-bold">{token ? "Definir nova senha" : "Recuperar senha"}</h1><p className="mt-2 text-sm text-slate-600">{token ? "Escolha uma nova senha com pelo menos 6 caracteres." : "Informe o seu e-mail para receber um link válido por 30 minutos."}</p><input className="mt-5 w-full rounded border p-2" type={token ? "password" : "email"} value={valor} onChange={(e) => setValor(e.target.value)} placeholder={token ? "Nova senha" : "E-mail"} required minLength={token ? 6 : undefined}/><button disabled={enviando} className="mt-4 w-full rounded bg-indigo-600 p-2 text-white disabled:opacity-60">{enviando ? "A enviar..." : "Continuar"}</button>{mensagem && <p className="mt-3 rounded bg-green-50 p-3 text-sm text-green-800">{mensagem}</p>}{erro && <p className="mt-3 rounded bg-red-50 p-3 text-sm text-red-700">{erro}</p>}<p className="mt-4 text-center text-sm"><Link className="text-indigo-600 underline" to="/login">Voltar ao login</Link></p></form></main>;
}
