import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { API_URL as API } from "../api/authenticatedFetch";
import { Feedback } from "./ui/Feedback";
export default function RecuperarSenha() {
  const navigate = useNavigate();
  const token = new URLSearchParams(window.location.search).get("token");
  const [valor, setValor] = useState(""); const [mensagem, setMensagem] = useState(""); const [erro, setErro] = useState(""); const [enviando, setEnviando] = useState(false); const [linkDesenvolvimento, setLinkDesenvolvimento] = useState("");
  const enviar = async (event) => { event.preventDefault(); setErro(""); setMensagem(""); setLinkDesenvolvimento(""); setEnviando(true); try { const r = await fetch(`${API}${token ? "/auth/redefinir-senha" : "/auth/recuperar-senha"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(token ? { token, senha: valor } : { email: valor }) }); const d = await r.json(); if (!r.ok) throw new Error(d.message || d.erro || "Não foi possível concluir a solicitação."); if (token) { navigate("/login", { replace: true, state: { senhaRedefinida: true } }); return; } setMensagem(d.message); setLinkDesenvolvimento(d.link_desenvolvimento || ""); } catch (error) { setErro(error.message); } finally { setEnviando(false); } };
  return <main className="grid min-h-screen place-items-center bg-slate-50 p-4"><form onSubmit={enviar} className="w-full min-w-0 max-w-md rounded-2xl bg-white p-5 shadow sm:p-7"><h1 className="text-xl font-bold">{token ? "Definir nova senha" : "Recuperar senha"}</h1><p className="mt-2 text-sm leading-6 text-slate-600">{token ? "Escolha uma nova senha com pelo menos 8 caracteres." : "Enviaremos um link de recuperação válido por 30 minutos. Verifique também a pasta de spam."}</p><label className="mt-5 block text-sm font-medium text-slate-700">{token ? "Nova senha" : "E-mail"}<input className="mt-1 w-full rounded-lg border border-slate-300 p-2.5" type={token ? "password" : "email"} value={valor} onChange={(e) => setValor(e.target.value)} autoComplete={token ? "new-password" : "email"} required minLength={token ? 8 : undefined}/></label><button disabled={enviando} className="mt-4 w-full rounded-lg bg-indigo-600 p-2.5 font-semibold text-white disabled:opacity-60">{enviando ? "A enviar..." : token ? "Guardar nova senha" : "Enviar link de recuperação"}</button><Feedback tipo="sucesso" className="mt-3">{mensagem}</Feedback>{linkDesenvolvimento && <a href={linkDesenvolvimento} className="mt-3 block w-full rounded-lg border border-indigo-200 bg-indigo-50 p-2.5 text-center text-sm font-bold text-indigo-700 hover:bg-indigo-100">Abrir link de recuperação local</a>}<Feedback tipo="erro" className="mt-3">{erro}</Feedback>{!token && mensagem && <button type="submit" disabled={enviando} className="mt-3 w-full text-sm font-semibold text-indigo-600 hover:underline">Reenviar e-mail</button>}<p className="mt-4 text-center text-sm"><Link className="text-indigo-600 underline" to="/login">Voltar ao login</Link></p></form></main>;
}
