CREATE TABLE IF NOT EXISTS AdministradorPlataforma (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_administrador_plataforma_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
