-- Migração para dados legais de empresa em bases existentes.
ALTER TABLE Empresa
  ADD COLUMN IF NOT EXISTS nuit VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS email VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS telefone VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS endereco VARCHAR(255) DEFAULT NULL;
